language: node_js
node_js:
    - "11.6.0"
script:
    - npm run build
deploy:
    local-dir: ./build
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
    keep-history: true
    repo: social-dist0rtion-protocol/planet-a-www
    # Note: Use this later when we've registered a cool domain
    #fqdn: 0xdeface.me
    target-branch: master
    on:
        branch: master
